"""
Quiz Model

Responsibility: Defines the Quiz ORM model for persisted quizzes generated by AI.
Layer: Model
Domain: Quiz
"""

from sqlalchemy import Column, DateTime, ForeignKey, String, Text, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from core.database import Base


class Quiz(Base):
    __tablename__ = "quizzes"

    id = Column(UUID(as_uuid=True), primary_key=True, index=True, server_default=text("gen_random_uuid()"))
    child_profile_id = Column(
        UUID(as_uuid=True),
        ForeignKey("child_profiles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    subject = Column(String(255), nullable=False)
    topic = Column(String(255), nullable=False)
    level = Column(String(50), nullable=False)
    intro = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    child_profile = relationship("ChildProfile", back_populates="quizzes")
    questions = relationship(
        "QuizQuestion",
        back_populates="quiz",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    result = relationship(
        "QuizResult",
        back_populates="quiz",
        uselist=False,
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
